language: python
dist: xenial
python:
- '3.7'
env:
  matrix:
  - MONGO_URL=mongodb://nebula:nebula@127.0.0.1:27017/nebula?authSource=admin
  - DOCKER_HUB_ORG=nebulaorchestrator
  - DOCKER_HUB_REPO=reporter
  global:
  - secure: teZI28CubTlE1OpTB7wkPzk8GjIiwJp3ksMzddrbV59xMcQlzok5zIJvhw0LWf5L4EHSlJht8BtD0/8PbCafBENACT/x5bTl5Ru3aHsZftmbOJW6C8pALdE/N09Xw/NH/6yVaDS/FdtI6W1/ldTtAP2PNiEpLQm9tvg3n5ye0MHMtPRxwEQ2iWjbiWOZVxgfDpP6/A5UPe5cmlUimcELM/ctGym/LDSNO/XJnwapWpSGvjFMuTqU1JH9OTvyD3Bvhy1rSPhvFomyD2Yk77dhuKloU0O1l5KxvF1RzGffGMu8xTZWHMRiuE8/Myl/hBH+PCmAgHwRGSieqfr+9LgwvfIw22UBYn3ySpZ596SulMst+/rwLZ1inxwxg75jHE2xWJWmGyM3TT1TJ9hD1CAkPFs+5UIO1kF6gYk7TG85mtA7avGsflAivQu8qDjqVmJEl7lvHSKM1wauj3790aLXUtP1odjvd/CcCUaJ6+NrpwuItg07KEfnb0CJzyfFMmuGwP441x1qo8I7woaEitLR0fLhODomAyUb4MkmNo0Ntq9shlaJNmcXZdJ7KHwd82t48qTGspi2s6K/ZwzyAl6Kio0izd9NQIb9wiHlWHL83xhetbSNR4wkyz24qWI35mwoI0X/aXrCwwUl1xj0chgqVz5BY/2puoyGuIj5qKN1CL4=
  - secure: uwECiToau8OXCUbmd/ZMyeIDqHGMAq/WE+SBHZ/yqAhEQJ5b5G5B/8tuZPdP9GQeWVj+7469gS9zEhLrXR3ux9fIkJRWDW7alLBkxnul5pisv95GeTa2oxKtDeB+Xikeb0ZXI06BT8n9GBVKAYokhE+GL55xxvZ2xjICjR+Z+YR7N/RhBU4xLnW6qUyVpS7oW1WuHMrYwWsTkX2ktYhnhrJjOWDM+4nEHlH5XM0fDGn5PXxTiPM/8bhQFo/8/gPnK4gQCFdV4dD9OdL3TlCodpPv77jcUdNWIlXilt2eAPbjJKZvC26JpA5TQP9RcaYDYCStGtbi49uiZ7Ay6mL9q/u0G6Yf75vUTHL/jGiZH7FPBu6bvpM1jVoBKRJr3BK1aYu/pJPAIPcsSPDb5rSno1f0T7TrPl4EFzI6NxwT73hQG3K9Pu33mn9KXA4Ags2YoR7Ov194z7b95N0RIDo0k+qKHjpWSTnxR+BiMDAWH2bXSh8QpKRts65hOC+WY2X1lhi4YD3euESKQxm4Ima/otcLmaXCwEvsvwHs4+qNCAvly4tInrJUer9j/65yAMQ38iBxwpf6oovXdd0qhVi3HtXgNouox97lc+C0VJEhqw2nGJd3vflsQcFU7w44WOd7aTNFTk9y0V91vO9phPfp/IQQ1zpqoq1dxLr1plAYC8k=
install:
- pip install -r requirements.txt
script:
- sudo sh test/travis_ci_scripts/travis_ci_build_script.sh
- python -m unittest discover
deploy:
  provider: script
  script: bash  test/travis_ci_scripts/deploy.sh
